# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e195ad2efd52f5b6e6deb7434e434ccfce0f45a69ed55111775e7a50f7556a6d1ca23225e0fcffc93080db5bf07de89b35427ca3d6c845f390a43bf28321bf

test:
  secret_key_base: 99336698634244694c26787daae04de175ebac78a4ee321f0df0fbbdb5665d9132c5702aacfedb7708a309982bc6fd433aa6bf9c6dbdb44aa88091e21557f4db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
